site_name: "Medial: návody pro uživatele"
site_url: https://kvet-divizny.github.io/medialdocs/

theme:
  name: material
  language: cs
  include_sidebar: true
  palette:
    primary: deep purple
  logo: assets/elf-inverze.svg
  features:
    - navigation.sections
markdown_extensions:
  - toc:
      toc_depth: 4
      permalink: true
  - attr_list
  - md_in_html
  - smarty

# Customization
extra_css:
  - stylesheets/extra.css

# Navigation
nav:
    - Domů: index.md
    - Základní přehled:
        - Co je to Medial: co-je-to-medial.md
        - Využití Medialu: vyuziti-medialu.md
        - Základní orientace: zakladni-orientace-v-medialu.md
        - Organizace obsahu: jak-je-obsah-v-medialu-organizovan.md
        - Propojení s Moodlem: propojeni-s-moodlem.md
    - Vkládání obsahu:
        - Nahrání souboru z počítače: jak-nahrat-do-medialu-soubor-z-pocitace.md
        - Záznam pomocí webkamery: jan-nahrat-video-pomoci-webkamery.md
        - Vkládání obsahu prostřednictvím Moodlu: jak-vkladat-obsah-prostrednictvim-moodlu.md
    - Správa obsahu:
        - Stránka Můj obsah: kde-najdu-vsechna-svoje-videa.md
        - Úprava nahrávek: jak-muazu-dodatecne-upravit-metadata.md
    - Sdílení obsahu:
        - Kdo může vidět můj obsah: kdo-muaze-videt-muaj-obsah.md
        - Sdílení obsahu: jak-muazu-sva-videa-sirit.md
    - Záznamy v učebnách:
        - Tlačítkové panely: tlacitkove-panely.md
        - Dotykové panely: dotykove-panely.md
        - Mikrofony: mikrofony.md
        - Živý přenos (live stream): zivy-prenos-live-stream.md
        - Kontakty: kontakty.md

