site_name: Medialdocs (test)
site_url: https://medial.phil.muni.cz
theme:
  name: material
  language: cs
  include_sidebar: true
  palette:
    primary: deep purple
  logo: assets/logo-cit-barva.svg
markdown_extensions:
  - toc:
      toc_depth: 4
  - attr_list
  - md_in_html
