site_name: Medialdocs (test)

theme:
  name: material
  language: cs
  include_sidebar: true
  palette:
    primary: deep purple
  logo: assets/elf-inverze.svg
markdown_extensions:
  - toc:
      toc_depth: 4
      permalink: true
  - attr_list
  - md_in_html
