name: github_ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      
      - name: Deploy
      - uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      - run: pip install mkdocs-rtd-dropdown
      - run: mkdocs gh-deploy --force
